export const routes = {
  home: "/",
  about: "/about",
  programs: "/programs",
  getInvolved: "/get-involved",
  donate: "/donate",
  faq: "/faq",
  contact: "/contact",
  enroll: "/enroll",
  enrollParent: "/enroll/parent",
  join: "/join",
  auth: {
    login: "/login",
    signup: "/signup",
    forgotPassword: "/forgot-password",
    setPassword: "/set-password",
    callback: "/auth/callback",
  },
  portal: {
    dashboard: "/dashboard",
    applicants: "/dashboard/applicants",
    students: "/dashboard/students",
    tutors: "/dashboard/tutors",
    volunteers: "/dashboard/volunteers",
    lessons: "/dashboard/lessons",
    availability: "/dashboard/availability",
    practice: "/dashboard/practice",
    assignments: "/dashboard/assignments",
    resources: "/dashboard/resources",
    calendar: "/dashboard/calendar",
    events: "/dashboard/events",
    tutorStudents: "/dashboard/tutor/students",
    tutorStudent: (studentId: string) =>
      `/dashboard/tutor/students/${studentId}` as const,
    volunteerHours: "/dashboard/volunteer/hours",
    volunteerCertificates: "/dashboard/volunteer/certificates",
    messages: "/dashboard/messages",
    messageThread: (id: string) => `/dashboard/messages/${id}` as const,
    messagesAudit: "/dashboard/messages/audit",
    announcements: "/dashboard/announcements",
    admin: {
      chapters: "/dashboard/admin/chapters",
      roles: "/dashboard/admin/roles",
      families: "/dashboard/admin/families",
      tutorAssignments: "/dashboard/admin/tutor-assignments",
      docs: "/dashboard/admin/docs",
      volunteerHours: "/dashboard/admin/volunteer-hours",
      announcements: "/dashboard/admin/announcements",
      donations: "/dashboard/admin/donations",
      auditLogs: "/dashboard/admin/audit-logs",
    },
  },
} as const
